---

name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run lint
      run: cargo clippy

  windows-check:
    runs-on: self-hosted
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-msvc
          toolchain: stable
          override: true
      - uses: actions/checkout@v2
      - name: Check Windows
        run: cargo check --target x86_64-pc-windows-msvc
